---
- name: Converge
  hosts: all
  become: true
  vars:
    ssh_default_private_key: "{{ lookup('env', 'SSH_DEFAULT_PRIVATE_KEY') }}"
    ssh_default_public_key: "{{ lookup('env', 'SSH_DEFAULT_PUBLIC_KEY') }}"
    ssh_gitlab_usernames:
      - thuvh
    ssh_manual_public_keys:
      - 'ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXe
        vct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQ
        PyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKc
        F96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== insecure public key'
    ssh_username: batman
    ssh_user_groups: sudo
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'

  roles:
    - role: thuvh.ssh
